//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA.Localization.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CA.Localization.Locales.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About application version.
        /// </summary>
        public static string AppVersionInfo_About {
            get {
                return ResourceManager.GetString("AppVersionInfo_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string AppVersionInfo_btnOkay_Text {
            get {
                return ResourceManager.GetString("AppVersionInfo_btnOkay_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string AppVersionInfo_lblCompanyName_Text {
            get {
                return ResourceManager.GetString("AppVersionInfo_lblCompanyName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string AppVersionInfo_lblCopyright_Text {
            get {
                return ResourceManager.GetString("AppVersionInfo_lblCopyright_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        public static string AppVersionInfo_lblProductName_Text {
            get {
                return ResourceManager.GetString("AppVersionInfo_lblProductName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AppVersionInfo_lblVersion_Text {
            get {
                return ResourceManager.GetString("AppVersionInfo_lblVersion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular automata.
        /// </summary>
        public static string AppVersionInfo_Text {
            get {
                return ResourceManager.GetString("AppVersionInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string AppVersionInfo_txbDescription_Text {
            get {
                return ResourceManager.GetString("AppVersionInfo_txbDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of the application.
        /// </summary>
        public static string AppVersionInfo_Version {
            get {
                return ResourceManager.GetString("AppVersionInfo_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string btnGetCell_Text {
            get {
                return ResourceManager.GetString("btnGetCell_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string btnSetCell_Text {
            get {
                return ResourceManager.GetString("btnSetCell_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerated successfully.
        /// </summary>
        public static string CellFieldUI_AllCompliteBox_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_AllCompliteBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string CellFieldUI_AllCompliteBox_Title {
            get {
                return ResourceManager.GetString("CellFieldUI_AllCompliteBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        public static string CellFieldUI_btnAccelerate_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnAccelerate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string CellFieldUI_btnApplyemulatorRules_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnApplyemulatorRules_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all planes.
        /// </summary>
        public static string CellFieldUI_btnClearAllMatrices_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnClearAllMatrices_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selectetd matrix.
        /// </summary>
        public static string CellFieldUI_btnClearSelectedPlane_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnClearSelectedPlane_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display content.
        /// </summary>
        public static string CellFieldUI_btnDisplayContent_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnDisplayContent_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string CellFieldUI_btnExit_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnExit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next generation.
        /// </summary>
        public static string CellFieldUI_btnGoToNextGeneration_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnGoToNextGeneration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create histogram.
        /// </summary>
        public static string CellFieldUI_btnMakeGistogramma_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnMakeGistogramma_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show graph.
        /// </summary>
        public static string CellFieldUI_btnShowGraph_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnShowGraph_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        public static string CellFieldUI_btnSlowDown_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnSlowDown_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string CellFieldUI_btnStart_Stop_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnStart_Stop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string CellFieldUI_btnStart_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start random generation.
        /// </summary>
        public static string CellFieldUI_btnStartGenerateRandomPattern_Start {
            get {
                return ResourceManager.GetString("CellFieldUI_btnStartGenerateRandomPattern_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop random generation.
        /// </summary>
        public static string CellFieldUI_btnStartGenerateRandomPattern_Stop {
            get {
                return ResourceManager.GetString("CellFieldUI_btnStartGenerateRandomPattern_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start random generation.
        /// </summary>
        public static string CellFieldUI_btnStartGenerateRandomPattern_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnStartGenerateRandomPattern_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set start point.
        /// </summary>
        public static string CellFieldUI_btnStartPoint_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnStartPoint_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap matrices.
        /// </summary>
        public static string CellFieldUI_btnSwapMatrices_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_btnSwapMatrices_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Configuration.
        /// </summary>
        public static string CellFieldUI_camOptions_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_camOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string CellFieldUI_CellValue {
            get {
                return ResourceManager.GetString("CellFieldUI_CellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of a cell.
        /// </summary>
        public static string CellFieldUI_gbCellsSize_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_gbCellsSize_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field location.
        /// </summary>
        public static string CellFieldUI_gbFieldLocation_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_gbFieldLocation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random pattern for selected matrix.
        /// </summary>
        public static string CellFieldUI_gbGenerateRandomPattern_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_gbGenerateRandomPattern_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string CellFieldUI_gbGraphs_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_gbGraphs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інтервал народження потомства.
        /// </summary>
        public static string CellFieldUI_gbIntervalForBirth_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_gbIntervalForBirth_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lifetime.
        /// </summary>
        public static string CellFieldUI_gbLifeDuration_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_gbLifeDuration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string CellFieldUI_gbMessage_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_gbMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview matrices content.
        /// </summary>
        public static string CellFieldUI_gbPlanesToShow_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_gbPlanesToShow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of starvation for predators.
        /// </summary>
        public static string CellFieldUI_gbPredatorsConf_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_gbPredatorsConf_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select matrix to change.
        /// </summary>
        public static string CellFieldUI_gbSelectPlane_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_gbSelectPlane_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change generations automatically.
        /// </summary>
        public static string CellFieldUI_gpbAutoTransitions_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_gpbAutoTransitions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell size mode (mashine state will be set to default!).
        /// </summary>
        public static string CellFieldUI_lblCellsSize_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_lblCellsSize_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Configuration.
        /// </summary>
        public static string CellFieldUI_lblEmulatorConfiguration_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_lblEmulatorConfiguration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herbivorous.
        /// </summary>
        public static string CellFieldUI_lblHerbivorous_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_lblHerbivorous_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predators.
        /// </summary>
        public static string CellFieldUI_lblPredators_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_lblPredators_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string CellFieldUI_lblSpeed_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_lblSpeed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string CellFieldUI_ok_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_ok_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string CellFieldUI_rbPlane0_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_rbPlane0_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string CellFieldUI_rbPlane1_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_rbPlane1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string CellFieldUI_rbPlane2_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_rbPlane2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string CellFieldUI_rbPlane3_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_rbPlane3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string CellFieldUI_rbPlane8_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_rbPlane8_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular atomata machine.
        /// </summary>
        public static string CellFieldUI_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        public static string CellFieldUI_tpAnalytics_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tpAnalytics_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix details.
        /// </summary>
        public static string CellFieldUI_tpDemography_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tpDemography_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrices.
        /// </summary>
        public static string CellFieldUI_tpFieldOptions_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tpFieldOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control panel.
        /// </summary>
        public static string CellFieldUI_tpMainControlBox_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tpMainControlBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string CellFieldUI_tsbClearSelectedPlane_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsbClearSelectedPlane_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selected matrix.
        /// </summary>
        public static string CellFieldUI_tsbClearSelectedPlane_ToolTipText {
            get {
                return ResourceManager.GetString("CellFieldUI_tsbClearSelectedPlane_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do transition one step.
        /// </summary>
        public static string CellFieldUI_tsbDoTransition_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsbDoTransition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do transitions in the background.
        /// </summary>
        public static string CellFieldUI_tsbDoTransition_ToolTipText {
            get {
                return ResourceManager.GetString("CellFieldUI_tsbDoTransition_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CellFieldUI_tsbsaveResultsToFile_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsbsaveResultsToFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save machine state to file.
        /// </summary>
        public static string CellFieldUI_tsbsaveResultsToFile_ToolTipText {
            get {
                return ResourceManager.GetString("CellFieldUI_tsbsaveResultsToFile_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select rules.
        /// </summary>
        public static string CellFieldUI_tsbSelectRules_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsbSelectRules_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select rules for machine.
        /// </summary>
        public static string CellFieldUI_tsbSelectRules_ToolTipText {
            get {
                return ResourceManager.GetString("CellFieldUI_tsbSelectRules_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set start point.
        /// </summary>
        public static string CellFieldUI_tsbSetStartPoint_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsbSetStartPoint_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set start point for statistics graph.
        /// </summary>
        public static string CellFieldUI_tsbSetStartPoint_ToolTipText {
            get {
                return ResourceManager.GetString("CellFieldUI_tsbSetStartPoint_ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About application.
        /// </summary>
        public static string CellFieldUI_tsmiAboutApp_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsmiAboutApp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More field options.
        /// </summary>
        public static string CellFieldUI_tsmiAdditionalFieldOptions_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsmiAdditionalFieldOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create histogram.
        /// </summary>
        public static string CellFieldUI_tsmiBuildHistogram_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsmiBuildHistogram_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new version.
        /// </summary>
        public static string CellFieldUI_tsmiCheckNewVersion_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsmiCheckNewVersion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create graph.
        /// </summary>
        public static string CellFieldUI_tsmiCreateGraph_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsmiCreateGraph_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply default configuration.
        /// </summary>
        public static string CellFieldUI_tsmiDefaultConfigurations_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsmiDefaultConfigurations_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        public static string CellFieldUI_tsmiExec_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsmiExec_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Other.
        /// </summary>
        public static string CellFieldUI_tsmiHelpCategory_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsmiHelpCategory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string CellFieldUI_tsmiSelectLanguage_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsmiSelectLanguage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change rules.
        /// </summary>
        public static string CellFieldUI_tsmiSetRules_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsmiSetRules_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string CellFieldUI_tsmiViewHelp_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsmiViewHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |    Progress of generations changing:.
        /// </summary>
        public static string CellFieldUI_tsslTransitionStatus_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_tsslTransitionStatus_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit app.
        /// </summary>
        public static string CellFieldUI_выходToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_выходToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load machine state from file.
        /// </summary>
        public static string CellFieldUI_загрузитьИзФайлаToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_загрузитьИзФайлаToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all fields.
        /// </summary>
        public static string CellFieldUI_новоеПолеToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_новоеПолеToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do transitions multiple times .
        /// </summary>
        public static string CellFieldUI_перейтиНаХХХПоколіньToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_перейтиНаХХХПоколіньToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save machine state to file.
        /// </summary>
        public static string CellFieldUI_сохранитьВФайлToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_сохранитьВФайлToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Main.
        /// </summary>
        public static string CellFieldUI_файлToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("CellFieldUI_файлToolStripMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells count.
        /// </summary>
        public static string Diagramme_lblCellsCount_Text {
            get {
                return ResourceManager.GetString("Diagramme_lblCellsCount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation.
        /// </summary>
        public static string Diagramme_lblGeneration_Text {
            get {
                return ResourceManager.GetString("Diagramme_lblGeneration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        public static string Diagramme_Text {
            get {
                return ResourceManager.GetString("Diagramme_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Diagramme_tsmiLegend_Text {
            get {
                return ResourceManager.GetString("Diagramme_tsmiLegend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        public static string GistogrammaOfCurrentPlane_btnOkay_Text {
            get {
                return ResourceManager.GetString("GistogrammaOfCurrentPlane_btnOkay_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cells.
        /// </summary>
        public static string GistogrammaOfCurrentPlane_lblCells_Text {
            get {
                return ResourceManager.GetString("GistogrammaOfCurrentPlane_lblCells_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string GistogrammaOfCurrentPlane_lblCount_Text {
            get {
                return ResourceManager.GetString("GistogrammaOfCurrentPlane_lblCount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View histogram.
        /// </summary>
        public static string GistogrammaOfCurrentPlane_lblGistogrammaView_Text {
            get {
                return ResourceManager.GetString("GistogrammaOfCurrentPlane_lblGistogrammaView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        public static string GistogrammaOfCurrentPlane_lblOfActive_Text {
            get {
                return ResourceManager.GetString("GistogrammaOfCurrentPlane_lblOfActive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram.
        /// </summary>
        public static string GistogrammaOfCurrentPlane_Text {
            get {
                return ResourceManager.GetString("GistogrammaOfCurrentPlane_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get or Set value of a cell.
        /// </summary>
        public static string lblCellValue {
            get {
                return ResourceManager.GetString("lblCellValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: {0}.
        /// </summary>
        public static string lblMouseCurrentPosition_Text {
            get {
                return ResourceManager.GetString("lblMouseCurrentPosition_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates are not correct.
        /// </summary>
        public static string LoadCellValueCoordinatesAreNotCorrect {
            get {
                return ResourceManager.GetString("LoadCellValueCoordinatesAreNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell value was not found.
        /// </summary>
        public static string LoadCellValueNotFound {
            get {
                return ResourceManager.GetString("LoadCellValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель збудження нейронів. Стимул активації комірки забезпечуєтся наявністю декількох сусідів, а клітини мають визначений час відтворення. В даній моделі використано від&apos;ємний зворотній зв&apos;язок..
        /// </summary>
        public static string Rules_AntiWorm_Description {
            get {
                return ResourceManager.GetString("Rules_AntiWorm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нейронна мережа.
        /// </summary>
        public static string Rules_AntiWorm_Name {
            get {
                return ResourceManager.GetString("Rules_AntiWorm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найпростіший підхід Бенкса, придатний для побудови обчислювальних схем довільного рівня складності. Якщо кількість сусідів в стані 1 (без врахування стану центральної комірки) рівно двом, то потрібно визначити як вони розташовані, якщо під кутом 90 то центральна комірка обнуляється. Плідно працювали в цьому напрямі: Джон Фон Нейман, Бенкс, Кодд Е.Ф. Зокрема Фон Нейман побудував обчислювального/самовідтворюючого робота..
        /// </summary>
        public static string Rules_BenksComp_Description {
            get {
                return ResourceManager.GetString("Rules_BenksComp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комп&apos;ютер Бенкса.
        /// </summary>
        public static string Rules_BenksComp_Name {
            get {
                return ResourceManager.GetString("Rules_BenksComp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель розвитку двох видів - травоїдних та хижаків. Дозволяє досліджувати процеси демографічного розвитку..
        /// </summary>
        public static string Rules_Demografia_Description {
            get {
                return ResourceManager.GetString("Rules_Demografia_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Боротьба за виживання.
        /// </summary>
        public static string Rules_Demographiya_Name {
            get {
                return ResourceManager.GetString("Rules_Demographiya_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правило запропоноване Чарлзом Беннетом, обмежене дифузією агрегуванняколи частинки налипають на початковий зародок, і помалу нарощують його. Моделі дендритного розвитку апроксимують фізичні процеси росту речовини (матеріал росту з&apos;являється ззовні, або зникає побічний продукт росту - напр. тепло)..
        /// </summary>
        public static string Rules_Dendrit_Description {
            get {
                return ResourceManager.GetString("Rules_Dendrit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розвиток дендритів.
        /// </summary>
        public static string Rules_Dendrit_Name {
            get {
                return ResourceManager.GetString("Rules_Dendrit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель щільних газів з врахуванням зіткнень зафарбованих частинок. Модель дозволяє досліджувати реальні процеси дифузії та  встановлення теплової рівноваги..
        /// </summary>
        public static string Rules_GM_GAS_Description {
            get {
                return ResourceManager.GetString("Rules_GM_GAS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приклад GM - газу.
        /// </summary>
        public static string Rules_GM_GAS_Name {
            get {
                return ResourceManager.GetString("Rules_GM_GAS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це правило має декілька типів активності, залежних від початкових умов.Правило розраховане Грінбергом Дж. та С. Гастінгом. Дозволяе вивчати поведінку хвиль різних частот..
        /// </summary>
        public static string Rules_GreenbergEndGastings_Description {
            get {
                return ResourceManager.GetString("Rules_GreenbergEndGastings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закон Грінберга і Гастінгса.
        /// </summary>
        public static string Rules_GreenbergEndGastings_Name {
            get {
                return ResourceManager.GetString("Rules_GreenbergEndGastings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic Oscillator.
        /// </summary>
        public static string Rules_HarmonicOscillator_Description {
            get {
                return ResourceManager.GetString("Rules_HarmonicOscillator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonic Oscillator.
        /// </summary>
        public static string Rules_HarmonicOscillator_Name {
            get {
                return ResourceManager.GetString("Rules_HarmonicOscillator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель дифузії щільних газів, без врахування зіткнень зафарбованих частинок.
        /// </summary>
        public static string Rules_Naiv_Deffusion_Description {
            get {
                return ResourceManager.GetString("Rules_Naiv_Deffusion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наївна дифузія.
        /// </summary>
        public static string Rules_Naiv_Deffusion_Name {
            get {
                return ResourceManager.GetString("Rules_Naiv_Deffusion_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зв&apos;язок між минулим та майбутнім. Простий приклад зворотності. Виконуется логічне \&quot;або\&quot; центральної комірки чотирьох її сусідів, та центральної комірки минулого покоління..
        /// </summary>
        public static string Rules_ParityFlip_Description {
            get {
                return ResourceManager.GetString("Rules_ParityFlip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Експеремент зв&apos;язку між минулим та майбутнім.
        /// </summary>
        public static string Rules_ParityFlip_Name {
            get {
                return ResourceManager.GetString("Rules_ParityFlip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примітивний ємулятор дифузії. Комірки дифундують вздовж горизонтальних ліній..
        /// </summary>
        public static string Rules_Primitiv_Deffusion_Description {
            get {
                return ResourceManager.GetString("Rules_Primitiv_Deffusion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примітивна дифузія.
        /// </summary>
        public static string Rules_Primitiv_Deffusion_Name {
            get {
                return ResourceManager.GetString("Rules_Primitiv_Deffusion_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking destruction in evolution of two equal not synchronized systems.
        /// </summary>
        public static string Rules_Rac_Description {
            get {
                return ResourceManager.GetString("Rules_Rac_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking destruction in evolution of two equal not synchronized systems.
        /// </summary>
        public static string Rules_Rac_Name {
            get {
                return ResourceManager.GetString("Rules_Rac_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приклад системи другого порядку - де наступна конфігурація є функцією теперішньої і минулої конфігурацій, тобто, при визначенні подальшої траекторії використовується пара послідовних конфігурацій. Зворотністі системи дозволяє на її базі моделювати процеси Нь&apos;ютонівської механіки. Автор - Ед Френкін, Масачусетський технологічний інститут..
        /// </summary>
        public static string Rules_Silverman_Description {
            get {
                return ResourceManager.GetString("Rules_Silverman_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cистеми другого порядку.
        /// </summary>
        public static string Rules_Silverman_Name {
            get {
                return ResourceManager.GetString("Rules_Silverman_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;Нипроникний бар&apos;ер\&quot;. Якщо задати початкову конфігурацію як фігуру з одиниць в обох массивах, отримаемо непроникний бар&apos;ер. Ще один приклад подорожі в часі....
        /// </summary>
        public static string Rules_Time_Tunnel_Description {
            get {
                return ResourceManager.GetString("Rules_Time_Tunnel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тунель у часі.
        /// </summary>
        public static string Rules_Time_Tunnel_Name {
            get {
                return ResourceManager.GetString("Rules_Time_Tunnel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модель розрідженого газу з врахуванням зіткнень частинок, та зіткнень частинок з стінками пробірки. Автор Норман Марголус (Масачусетський технологічний інститут)..
        /// </summary>
        public static string Rules_TM_GAS_Description {
            get {
                return ResourceManager.GetString("Rules_TM_GAS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приклад TM - газу.
        /// </summary>
        public static string Rules_TM_GAS_Name {
            get {
                return ResourceManager.GetString("Rules_TM_GAS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ведіть числа, що відповідають кількості сусідів, розділені комами.  Наприклад: 1,3,6-9.
        /// </summary>
        public static string Rules_UserOptions_Description {
            get {
                return ResourceManager.GetString("Rules_UserOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom rules.
        /// </summary>
        public static string Rules_UserOptions_Name {
            get {
                return ResourceManager.GetString("Rules_UserOptions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правило виведене Геральдом Вішняком, полягае в \&quot;голосуванні клітин\&quot;. Є базою при побудві моделей континуальних явищ поверхневого натягу..
        /// </summary>
        public static string Rules_VishnaksOptions_Description {
            get {
                return ResourceManager.GetString("Rules_VishnaksOptions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поверхневий натяг.
        /// </summary>
        public static string Rules_VishnaksOptions_Name {
            get {
                return ResourceManager.GetString("Rules_VishnaksOptions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Model files (*.camodel)|*.camodel|All files (*.*)|*.*.
        /// </summary>
        public static string SaveFileDlg_Filter {
            get {
                return ResourceManager.GetString("SaveFileDlg_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current rules:.
        /// </summary>
        public static string SelectedRules {
            get {
                return ResourceManager.GetString("SelectedRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        public static string SelectRules_btnOkay_Text {
            get {
                return ResourceManager.GetString("SelectRules_btnOkay_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select rules for CA machine.
        /// </summary>
        public static string SelectRules_gbSelectRules_Text {
            get {
                return ResourceManager.GetString("SelectRules_gbSelectRules_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For birth.
        /// </summary>
        public static string SelectRules_lblBirthRules_Text {
            get {
                return ResourceManager.GetString("SelectRules_lblBirthRules_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For survival.
        /// </summary>
        public static string SelectRules_lblSurvivalRules_Text {
            get {
                return ResourceManager.GetString("SelectRules_lblSurvivalRules_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure rules.
        /// </summary>
        public static string SelectRules_Text {
            get {
                return ResourceManager.GetString("SelectRules_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string TuningOfTheField_btnAgree_Text {
            get {
                return ResourceManager.GetString("TuningOfTheField_btnAgree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TuningOfTheField_btnCancel_Text {
            get {
                return ResourceManager.GetString("TuningOfTheField_btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show cell borders (unavailable for pixel cell size).
        /// </summary>
        public static string TuningOfTheField_chbDontShowInnerBorders_Text {
            get {
                return ResourceManager.GetString("TuningOfTheField_chbDontShowInnerBorders_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string TuningOfTheField_gbOptions_Text {
            get {
                return ResourceManager.GetString("TuningOfTheField_gbOptions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell size mode (mashine state will be set to default!).
        /// </summary>
        public static string TuningOfTheField_lblCellSize_Text {
            get {
                return ResourceManager.GetString("TuningOfTheField_lblCellSize_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field size (pixels).
        /// </summary>
        public static string TuningOfTheField_lblFieldSize_Text {
            get {
                return ResourceManager.GetString("TuningOfTheField_lblFieldSize_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular automata machine \n April 2008р..
        /// </summary>
        public static string TuningOfTheField_MainText {
            get {
                return ResourceManager.GetString("TuningOfTheField_MainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cofigure field options.
        /// </summary>
        public static string TuningOfTheField_Text {
            get {
                return ResourceManager.GetString("TuningOfTheField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get version information from the server. Please check your internet connection or firewall rules..
        /// </summary>
        public static string Updater_ErrorMessage_Text {
            get {
                return ResourceManager.GetString("Updater_ErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Updater_ErrorMessage_Title {
            get {
                return ResourceManager.GetString("Updater_ErrorMessage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version available. Do you want to upload it?.
        /// </summary>
        public static string Updater_Update_AvailableNewVersion {
            get {
                return ResourceManager.GetString("Updater_Update_AvailableNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new verions available.
        /// </summary>
        public static string Updater_Update_NotAvailable {
            get {
                return ResourceManager.GetString("Updater_Update_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for new versions.
        /// </summary>
        public static string Updater_Update_Title {
            get {
                return ResourceManager.GetString("Updater_Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update to new version.
        /// </summary>
        public static string Updater_UpdateMessage {
            get {
                return ResourceManager.GetString("Updater_UpdateMessage", resourceCulture);
            }
        }
    }
}
